using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.SignalR;

namespace SignalrChat
{

    //inherit any class  from hub and implement any method, a proxy will automatically be created for each method in script generated by signalr http://localhost:65514/signalr/hubs
    //in html create a method to be called by signalr of same signature and thena method where u send message back to server
    public class ChatHub : Hub
    {
        public void Hello()
        {
            Clients.All.hello();
        }
        public void Send(string name, string message)
        {
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, message);
        }
    }
    public class MyHub :Hub
    {
        public void Hello()
        {
            Clients.All.hello();
        }
        public void Send(string name, string message)
        {
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, ":aJ:"+message);
        }
    }
}