//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace As24WebServicesTest.As24Lookup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(As24WebServicesTest.As24Lookup.GetMakeModelTreeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(As24WebServicesTest.As24Lookup.GetLookupDataRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string culture_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profile_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int revisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((object.ReferenceEquals(this.client_idField, value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string culture_id {
            get {
                return this.culture_idField;
            }
            set {
                if ((object.ReferenceEquals(this.culture_idField, value) != true)) {
                    this.culture_idField = value;
                    this.RaisePropertyChanged("culture_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profile_id {
            get {
                return this.profile_idField;
            }
            set {
                if ((object.ReferenceEquals(this.profile_idField, value) != true)) {
                    this.profile_idField = value;
                    this.RaisePropertyChanged("profile_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int revision {
            get {
                return this.revisionField;
            }
            set {
                if ((this.revisionField.Equals(value) != true)) {
                    this.revisionField = value;
                    this.RaisePropertyChanged("revision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMakeModelTreeRequest", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class GetMakeModelTreeRequest : As24WebServicesTest.As24Lookup.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> dealer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string as24_customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> group_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicle_type_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> dealer_id {
            get {
                return this.dealer_idField;
            }
            set {
                if ((this.dealer_idField.Equals(value) != true)) {
                    this.dealer_idField = value;
                    this.RaisePropertyChanged("dealer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string as24_customer_id {
            get {
                return this.as24_customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.as24_customer_idField, value) != true)) {
                    this.as24_customer_idField = value;
                    this.RaisePropertyChanged("as24_customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<int> group_id {
            get {
                return this.group_idField;
            }
            set {
                if ((this.group_idField.Equals(value) != true)) {
                    this.group_idField = value;
                    this.RaisePropertyChanged("group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vehicle_type_id {
            get {
                return this.vehicle_type_idField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicle_type_idField, value) != true)) {
                    this.vehicle_type_idField = value;
                    this.RaisePropertyChanged("vehicle_type_id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupDataRequest", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class GetLookupDataRequest : As24WebServicesTest.As24Lookup.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicle_type_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string vehicle_type_id {
            get {
                return this.vehicle_type_idField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicle_type_idField, value) != true)) {
                    this.vehicle_type_idField = value;
                    this.RaisePropertyChanged("vehicle_type_id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(As24WebServicesTest.As24Lookup.GetMakeModelTreeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(As24WebServicesTest.As24Lookup.GetLookupDataResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string request_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.error[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.Build buildField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string request_id {
            get {
                return this.request_idField;
            }
            set {
                if ((object.ReferenceEquals(this.request_idField, value) != true)) {
                    this.request_idField = value;
                    this.RaisePropertyChanged("request_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public As24WebServicesTest.As24Lookup.error[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public As24WebServicesTest.As24Lookup.Build build {
            get {
                return this.buildField;
            }
            set {
                if ((object.ReferenceEquals(this.buildField, value) != true)) {
                    this.buildField = value;
                    this.RaisePropertyChanged("build");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Build", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class Build : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.TimeStamp time_stampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public As24WebServicesTest.As24Lookup.TimeStamp time_stamp {
            get {
                return this.time_stampField;
            }
            set {
                if ((object.ReferenceEquals(this.time_stampField, value) != true)) {
                    this.time_stampField = value;
                    this.RaisePropertyChanged("time_stamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMakeModelTreeResponse", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class GetMakeModelTreeResponse : As24WebServicesTest.As24Lookup.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.stx3_idpool stx3_idpoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public As24WebServicesTest.As24Lookup.stx3_idpool stx3_idpool {
            get {
                return this.stx3_idpoolField;
            }
            set {
                if ((object.ReferenceEquals(this.stx3_idpoolField, value) != true)) {
                    this.stx3_idpoolField = value;
                    this.RaisePropertyChanged("stx3_idpool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupDataResponse", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class GetLookupDataResponse : As24WebServicesTest.As24Lookup.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.stx3_idpool stx3_idpoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public As24WebServicesTest.As24Lookup.stx3_idpool stx3_idpool {
            get {
                return this.stx3_idpoolField;
            }
            set {
                if ((object.ReferenceEquals(this.stx3_idpoolField, value) != true)) {
                    this.stx3_idpoolField = value;
                    this.RaisePropertyChanged("stx3_idpool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="error", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stx3_idpool", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class stx3_idpool : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.element[] elementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.node[] nodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public As24WebServicesTest.As24Lookup.element[] elements {
            get {
                return this.elementsField;
            }
            set {
                if ((object.ReferenceEquals(this.elementsField, value) != true)) {
                    this.elementsField = value;
                    this.RaisePropertyChanged("elements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public As24WebServicesTest.As24Lookup.node[] nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeStamp", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class TimeStamp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string runtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string runtime {
            get {
                return this.runtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.runtimeField, value) != true)) {
                    this.runtimeField = value;
                    this.RaisePropertyChanged("runtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string service {
            get {
                return this.serviceField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceField, value) != true)) {
                    this.serviceField = value;
                    this.RaisePropertyChanged("service");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="element", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class element : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="node", Namespace="http://www.autoscout24.com/webapi/data/")]
    [System.SerializableAttribute()]
    public partial class node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private As24WebServicesTest.As24Lookup.node[] nodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public As24WebServicesTest.As24Lookup.node[] nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.autoscout24.com/webapi/", ConfigurationName="As24Lookup.ILookup")]
    public interface ILookup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.autoscout24.com/webapi/ILookup/GetLookupData", ReplyAction="http://www.autoscout24.com/webapi/ILookup/GetLookupDataResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        As24WebServicesTest.As24Lookup.GetLookupDataResponse GetLookupData(As24WebServicesTest.As24Lookup.GetLookupDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.autoscout24.com/webapi/ILookup/GetLookupData", ReplyAction="http://www.autoscout24.com/webapi/ILookup/GetLookupDataResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<As24WebServicesTest.As24Lookup.GetLookupDataResponse> GetLookupDataAsync(As24WebServicesTest.As24Lookup.GetLookupDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.autoscout24.com/webapi/ILookup/GetMakeModelTree", ReplyAction="http://www.autoscout24.com/webapi/ILookup/GetMakeModelTreeResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        As24WebServicesTest.As24Lookup.GetMakeModelTreeResponse GetMakeModelTree(As24WebServicesTest.As24Lookup.GetMakeModelTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.autoscout24.com/webapi/ILookup/GetMakeModelTree", ReplyAction="http://www.autoscout24.com/webapi/ILookup/GetMakeModelTreeResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<As24WebServicesTest.As24Lookup.GetMakeModelTreeResponse> GetMakeModelTreeAsync(As24WebServicesTest.As24Lookup.GetMakeModelTreeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILookupChannel : As24WebServicesTest.As24Lookup.ILookup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupClient : System.ServiceModel.ClientBase<As24WebServicesTest.As24Lookup.ILookup>, As24WebServicesTest.As24Lookup.ILookup {
        
        public LookupClient() {
        }
        
        public LookupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public As24WebServicesTest.As24Lookup.GetLookupDataResponse GetLookupData(As24WebServicesTest.As24Lookup.GetLookupDataRequest request) {
            return base.Channel.GetLookupData(request);
        }
        
        public System.Threading.Tasks.Task<As24WebServicesTest.As24Lookup.GetLookupDataResponse> GetLookupDataAsync(As24WebServicesTest.As24Lookup.GetLookupDataRequest request) {
            return base.Channel.GetLookupDataAsync(request);
        }
        
        public As24WebServicesTest.As24Lookup.GetMakeModelTreeResponse GetMakeModelTree(As24WebServicesTest.As24Lookup.GetMakeModelTreeRequest request) {
            return base.Channel.GetMakeModelTree(request);
        }
        
        public System.Threading.Tasks.Task<As24WebServicesTest.As24Lookup.GetMakeModelTreeResponse> GetMakeModelTreeAsync(As24WebServicesTest.As24Lookup.GetMakeModelTreeRequest request) {
            return base.Channel.GetMakeModelTreeAsync(request);
        }
    }
}
